name: CI for RIF-Relay-Client
on: [push]
jobs:
    lint_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3

            - name: Install dependencies
              run: npm install

            - name: Check Linter bugs
              run: npm run lint

            - name: Check Codestyles errors
              run: npm run format

            - name: Run test
              run: npm run test
